import 'package:flutter/material.dart';

ExactAssetImage appLogoWithNameImage = const ExactAssetImage('assets/images/logo@2x.png');
ExactAssetImage horizontalAppLogoDark = const ExactAssetImage('assets/images/horizontal_logo_name_dark.png',scale: 2.6);
ExactAssetImage horizontalAppLogoLight = const ExactAssetImage('assets/images/horizontal_logo_name_light.png',scale: 2.6);
ExactAssetImage appLogo = const ExactAssetImage('assets/images/sidis_logo@3x.png');
ExactAssetImage userNameImage = const ExactAssetImage('assets/images/user_name@2x.png',scale: 2);
ExactAssetImage passwordImage = const ExactAssetImage('assets/images/password@2x.png',scale: 2);
ExactAssetImage checkedImage = const ExactAssetImage('assets/images/remember_checked.png');
ExactAssetImage unCheckedImage = const ExactAssetImage('assets/images/remember_unchecked.png');
ExactAssetImage backIconImage = const ExactAssetImage('assets/images/back_icon.png');
ExactAssetImage forgotPasswordImage = const ExactAssetImage('assets/images/forgot_passs_word@2x.png');
ExactAssetImage menuIconImage = const ExactAssetImage('assets/images/menu_icon@2x.png',scale: 2);
ExactAssetImage nextPageArrowImage = const ExactAssetImage('assets/images/next_page_arrow.png');
ExactAssetImage watermarkImage = const ExactAssetImage('assets/images/watermark_logo.png');
ExactAssetImage assignedAbnormalityImage = const ExactAssetImage('assets/images/assigned_abnormality_icon@2x.png',scale: 2);
ExactAssetImage clitaActivityImage = const ExactAssetImage('assets/images/clita_activity@2x.png',scale: 2);
ExactAssetImage plantIconImage = const ExactAssetImage('assets/images/plant_icon@2x.png',scale: 2.5);

ExactAssetImage dashboardImage = const ExactAssetImage('assets/icons/Dashboard.png');
ExactAssetImage companiesImage = const ExactAssetImage('assets/icons/Companies@2x.png',scale: 2);
ExactAssetImage businessesImage = const ExactAssetImage('assets/icons/Bussinesses.png');
ExactAssetImage plantsImage = const ExactAssetImage('assets/icons/Plants.png');
ExactAssetImage departmentsImage = const ExactAssetImage('assets/icons/Departments.png');
ExactAssetImage machinesImage = const ExactAssetImage('assets/icons/Machines.png');
ExactAssetImage clitaActivityListImage = const ExactAssetImage('assets/icons/CLITA_Activity_List@2x.png',scale: 2);
ExactAssetImage clitaFillFormImage = const ExactAssetImage('assets/icons/CLITA_Fill_Form@2x.png',scale: 2);
ExactAssetImage clitaNoListImage = const ExactAssetImage('assets/icons/CLITA_No_List@2x.png',scale: 2);
ExactAssetImage abnormalityFormImage = const ExactAssetImage('assets/icons/Abnormality_Form@2x.png',scale: 2);
ExactAssetImage assignedFormImage = const ExactAssetImage('assets/icons/Assigned_Form@2x.png',scale: 2);
ExactAssetImage kaizenFormImage = const ExactAssetImage('assets/icons/Kaizen_Form@2x.png',scale: 2);
ExactAssetImage userManagementImage = const ExactAssetImage('assets/icons/User_Management@2x.png',scale: 2);
ExactAssetImage logoutImage = const ExactAssetImage('assets/icons/logout_button@2x.png',scale: 2);
