import 'package:flutter/material.dart';

ExactAssetImage splashBgImage = const ExactAssetImage('assets/images/splash_bg@2x.png');
ExactAssetImage appLogoWithNameImage = const ExactAssetImage('assets/images/logo@2x.png');
ExactAssetImage welcomeBgImage = const ExactAssetImage('assets/images/welcome_logo_top.png');
ExactAssetImage appLogo = const ExactAssetImage('assets/images/sidis_logo.png');
ExactAssetImage userNameImage = const ExactAssetImage('assets/images/user_name.png');
ExactAssetImage passwordImage = const ExactAssetImage('assets/images/password.png');
ExactAssetImage hidePasswordImage = const ExactAssetImage('assets/images/hide.png');
ExactAssetImage checkedImage = const ExactAssetImage('assets/images/remember_checked.png');
ExactAssetImage backIconImage = const ExactAssetImage('assets/images/back_icon.png');
ExactAssetImage forgotPasswordImage = const ExactAssetImage('assets/images/forgot_passs_word.png');
ExactAssetImage menuIconImage = const ExactAssetImage('assets/images/menu_icon.png');
ExactAssetImage nextPageArrowImage = const ExactAssetImage('assets/images/next_page_arrow.png');
ExactAssetImage watermarkImage = const ExactAssetImage('assets/images/watermark_logo.png');
ExactAssetImage assignedAbnormalityImage = const ExactAssetImage('assets/images/assigned_abnormality_icon.png');
ExactAssetImage clitaActivityImage = const ExactAssetImage('assets/images/clita_activity.png');
ExactAssetImage plantIconImage = const ExactAssetImage('assets/images/plant_icon.png',scale: 1.2);

ExactAssetImage dashboardImage = const ExactAssetImage('assets/icons/Dashboard.png');
ExactAssetImage companiesImage = const ExactAssetImage('assets/icons/Companies.png');
ExactAssetImage businessesImage = const ExactAssetImage('assets/icons/Bussinesses.png');
ExactAssetImage plantsImage = const ExactAssetImage('assets/icons/Plants.png');
ExactAssetImage departmentsImage = const ExactAssetImage('assets/icons/Departments.png');
ExactAssetImage machinesImage = const ExactAssetImage('assets/icons/Machines.png');
ExactAssetImage clitaActivityListImage = const ExactAssetImage('assets/icons/CLITA_Activity_List.png');
ExactAssetImage clitaFillFormImage = const ExactAssetImage('assets/icons/CLITA_Fill_Form.png');
ExactAssetImage clitaNoListImage = const ExactAssetImage('assets/icons/CLITA_No_List.png');
ExactAssetImage abnormalityFormImage = const ExactAssetImage('assets/icons/Abnormality_Form.png');
ExactAssetImage assignedFormImage = const ExactAssetImage('assets/icons/Assigned_Form.png');
ExactAssetImage kaizenFormImage = const ExactAssetImage('assets/icons/Kaizen_Form.png');
ExactAssetImage userManagementImage = const ExactAssetImage('assets/icons/User_Management.png');
ExactAssetImage logoutImage = const ExactAssetImage('assets/icons/logout_button.png');
